import { promises as fs } from "fs";
import path from "path";
import crypto from "crypto";

// Local file storage that simulates a connected Dropbox. Everything funnels
// through this module so swapping to the Dropbox API later is a single change.
//
// Folder layout mirrors what we'd create in Dropbox:
//   storage/projects/<projectId>/uploads/<file>
//   storage/projects/<projectId>/editor-brief.pdf

export const STORAGE_ROOT = path.join(process.cwd(), "storage");

export function projectFolder(projectId: string) {
  return path.join("projects", projectId);
}

/** A human-friendly "Dropbox path" we show in the UI. */
export function dropboxDisplayPath(projectTitle: string) {
  const safe = projectTitle.replace(/[\\/:*?"<>|]/g, "").trim();
  return `/RealTour Pilot/Shoots/${safe}`;
}

async function ensureDir(absDir: string) {
  await fs.mkdir(absDir, { recursive: true });
}

/** Persist an uploaded File and return its storage metadata. */
export async function saveUpload(projectId: string, file: File) {
  const buf = Buffer.from(await file.arrayBuffer());
  const rel = path.join(projectFolder(projectId), "uploads");
  const absDir = path.join(STORAGE_ROOT, rel);
  await ensureDir(absDir);

  const ext = path.extname(file.name);
  const storedName = `${crypto.randomUUID()}${ext}`;
  const storedRel = path.join(rel, storedName);
  await fs.writeFile(path.join(STORAGE_ROOT, storedRel), buf);

  return {
    originalName: file.name,
    storedPath: storedRel,
    size: buf.length,
    mimeType: file.type || "application/octet-stream",
  };
}

/** Write generated bytes (e.g. the editor PDF) and return the relative path. */
export async function writeFile(projectId: string, name: string, bytes: Uint8Array) {
  const rel = path.join(projectFolder(projectId), name);
  await ensureDir(path.join(STORAGE_ROOT, projectFolder(projectId)));
  await fs.writeFile(path.join(STORAGE_ROOT, rel), bytes);
  return rel;
}

export async function readFile(relPath: string) {
  return fs.readFile(path.join(STORAGE_ROOT, relPath));
}

export async function deleteFile(relPath: string) {
  await fs.rm(path.join(STORAGE_ROOT, relPath), { force: true });
}
