import "server-only";
import path from "path";
import crypto from "crypto";
import { dropboxUpload, dropboxDownload, dropboxDelete } from "./integrations/dropbox";

// Persistent file storage, backed by the connected company Dropbox. Vercel's
// filesystem is ephemeral (wiped between invocations), so anything we need to
// keep — uploaded files, generated docs — has to live in Dropbox, not on disk.
//
// Everything the app stores lives under ONE app-owned prefix so the /api/file
// route can hard-scope what it's willing to serve and never reach into the rest
// of the team's Dropbox.
export const STORAGE_PREFIX = "/RealTour Pilot/Hub";

/** True if a Dropbox path is inside our app-owned storage prefix. */
export function withinStorage(p: string): boolean {
  const norm = p.startsWith("/") ? p : "/" + p;
  return norm === STORAGE_PREFIX || norm.startsWith(STORAGE_PREFIX + "/");
}

/** A human-friendly "Dropbox path" we show in the UI for a shoot's media folder. */
export function dropboxDisplayPath(projectTitle: string) {
  const safe = projectTitle.replace(/[\\/:*?"<>|]/g, "").trim();
  return `/RealTour Pilot/Shoots/${safe}`;
}

function uploadsDir(projectId: string) {
  return `${STORAGE_PREFIX}/projects/${projectId}/uploads`;
}

/** Persist an uploaded File to Dropbox and return its storage metadata. */
export async function saveUpload(projectId: string, file: File) {
  const buf = Buffer.from(await file.arrayBuffer());
  const ext = path.extname(file.name);
  const storedPath = `${uploadsDir(projectId)}/${crypto.randomUUID()}${ext}`;
  await dropboxUpload(storedPath, buf);
  return {
    originalName: file.name,
    storedPath,
    size: buf.length,
    mimeType: file.type || "application/octet-stream",
  };
}

/** Write generated bytes (e.g. a document) to Dropbox; returns the stored path. */
export async function writeFile(projectId: string, name: string, bytes: Uint8Array) {
  const storedPath = `${STORAGE_PREFIX}/projects/${projectId}/${name}`;
  await dropboxUpload(storedPath, bytes, { overwrite: true });
  return storedPath;
}

export async function readFile(storedPath: string): Promise<Buffer> {
  return dropboxDownload(storedPath);
}

export async function deleteFile(storedPath: string): Promise<void> {
  await dropboxDelete(storedPath);
}
