import "server-only";
import path from "path";
import crypto from "crypto";
import { dropboxUpload, dropboxDownload, dropboxDelete } from "./integrations/dropbox";

// Persistent file storage, backed by the connected company Dropbox. Vercel's
// filesystem is ephemeral (wiped between invocations), so anything we need to
// keep — uploaded files, generated docs — has to live in Dropbox, not on disk.
//
// Everything the app stores lives under ONE app-owned prefix so the /api/file
// route can hard-scope what it's willing to serve and never reach into the rest
// of the team's Dropbox.
export const STORAGE_PREFIX = "/RealTour Pilot/Hub";

/**
 * True if a Dropbox path is inside our app-owned storage prefix.
 *
 * A ".." segment is refused outright (review, Sep 16). Dropbox resolves
 * nothing — it treats `…/projects/<id>/../../Personal/taxes.pdf` as a literal
 * name and answers 404 — so this is not an escape today. But this check is the
 * only thing standing between /api/file and the rest of the team's Dropbox,
 * and it must not quietly depend on a remote API's parsing staying literal.
 * It would also have let a traversal path pass the new "whose job is this?"
 * attribution by naming a real project id on its way out of the prefix.
 */
export function withinStorage(p: string): boolean {
  const norm = p.startsWith("/") ? p : "/" + p;
  if (norm.split("/").includes("..")) return false;
  return norm === STORAGE_PREFIX || norm.startsWith(STORAGE_PREFIX + "/");
}

/**
 * The project a stored path belongs to, read back out of the convention below
 * (`<prefix>/projects/<projectId>/…`). /api/file uses it to answer "whose file
 * is this?" for anything written here that has no UploadedFile row of its own
 * (RTP-01, Sep 16). Null when the path is ours but names no project — which
 * the route treats as a refusal, not as permission.
 */
export function projectIdFromStoragePath(p: string): string | null {
  if (!withinStorage(p)) return null;
  const norm = p.startsWith("/") ? p : "/" + p;
  const rest = norm.slice(STORAGE_PREFIX.length + 1); // drop the prefix and its "/"
  const [folder, projectId] = rest.split("/");
  return folder === "projects" && projectId ? projectId : null;
}

/** A human-friendly "Dropbox path" we show in the UI for a shoot's media folder. */
export function dropboxDisplayPath(projectTitle: string) {
  const safe = projectTitle.replace(/[\\/:*?"<>|]/g, "").trim();
  return `/RealTour Pilot/Shoots/${safe}`;
}

function uploadsDir(projectId: string) {
  return `${STORAGE_PREFIX}/projects/${projectId}/uploads`;
}

/** Persist an uploaded File to Dropbox and return its storage metadata. */
export async function saveUpload(projectId: string, file: File) {
  const buf = Buffer.from(await file.arrayBuffer());
  const ext = path.extname(file.name);
  const storedPath = `${uploadsDir(projectId)}/${crypto.randomUUID()}${ext}`;
  await dropboxUpload(storedPath, buf);
  return {
    originalName: file.name,
    storedPath,
    size: buf.length,
    mimeType: file.type || "application/octet-stream",
  };
}

/** Write generated bytes (e.g. a document) to Dropbox; returns the stored path. */
export async function writeFile(projectId: string, name: string, bytes: Uint8Array) {
  const storedPath = `${STORAGE_PREFIX}/projects/${projectId}/${name}`;
  await dropboxUpload(storedPath, bytes, { overwrite: true });
  return storedPath;
}

export async function readFile(storedPath: string): Promise<Buffer> {
  return dropboxDownload(storedPath);
}

export async function deleteFile(storedPath: string): Promise<void> {
  await dropboxDelete(storedPath);
}
